version: '2'
services:
  nginx:
    image: mritd/nginx-ext
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /etc/nginx/conf.d:/etc/nginx/conf.d
    links:
      - registry
    ports:
      - "80:80"
      - "443:443"
  registry:
    restart: always
    image: registry:2.5.1
    volumes:
      - /data/registry:/var/lib/registry
