version: '3'
services: 
  elasticsearch:
    container_name: es
    image: mritd/elasticsearch:6.2.1
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/usr/local/elasticsearch/config
