version: '2'
services:
  shadowsocks:
    image: mritd/shadowsocks:3.1.0
    container_name: shadowsocks
    restart: always
    ports:
      - "23:23"
      - "143:143/udp"    
      - "135:135"
    environment:
      - SS_MODULE
      - SS_CONFIG
      - KCP_MODULE
      - KCP_CONFIG
    command: -m "$SS_MODULE" -s "$SS_CONFIG" -k "$KCP_CONFIG" -e "$KCP_MODULE" -x 
