version: '2'
services:
  time-machine:
    image: mritd/time-machine
    restart: always
    container_name: time-machine
    network_mode: "host"
    volumes:
      - /data/time-machine:/data
    environment:
      - TM_CMD
    command: $TM_CMD
