version: '3.5'
services:
  nginx:
    image: nginx:1.13.12-alpine
    container_name: nginx
    restart: always
    networks:
      - nginx
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./conf.d:/etc/nginx/conf.d
      - ./log:/var/log/nginx/
      - ./vippasswd:/etc/nginx/conf/vippasswd
    ports:
      - "80:80"
      - "443:443"
networks:
  nginx:
    external:
      name: nginx
