version: '2' 
services:
  lightsocks:
    image: mritd/lightsocks:1.0.6
    container_name: lightsocks
    restart: always
    volumes: 
      - ./lightsocks.json:/root/.lightsocks.json 
    ports: 
      - "56:56" 
    environment:
      - LIGHT_MODULE
