version: '2'
services:
  cf-register-center:
    image: cf-register-center:latest
    build:
       context: ./cf-register-center
#       network: overlay
#       args: 
#        - jarName=cf-register-centr.jar
    volumes:
       - /app/logs:/app/logs
    privileged: true
    restart: always
    ports:
       - "8761:8761"
  cf-config-center:
    image: cf-config-center:latest
    build:
       context: ./cf-config-center
#       args: 
#        - jarName=cf-config-centr.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8019:8019"
    links:
       - cf-register-center
    restart: always
  cf-merchant-center:
    image: cf-merchant-center:latest
    build:
       context: ./cf-merchant-center
#       args: 
#        - jarName=cf-merchant-center.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8002:8002"
    links:
       - cf-register-center
    restart: always
  cf-user-center:
    image: cf-user-center:latest
    build:
       context: ./cf-user-center
#       args: 
#        - jarName=cf-config-centr.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8020:8020"
    links:
       - cf-register-center
    restart: always
  cf-admin:
    image: cf-admin:latest
    build:
       context: ./cf-admin
#       args: 
#        - jarName=cf-config-centr.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
    container_name: cf-admin-80
#    log-driver: syslog
    ports:
       - "8008:8008"
    links:
       - cf-register-center
    restart: always
  cf-biz-instcash:
    image: cf-biz-instcash:latest
    build:
       context: ./cf-biz-instcash
#       args: 
#        - jarName=cf-biz-instcash.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8033:8033"
    links:
       - cf-register-center
    restart: always
  cf-biz-instchannel:
    image: cf-biz-instchannel:latest
    build:
       context: ./cf-biz-instchannel
#       args: 
#        - jarName=cf-biz-instchannel.jar
    volumes:
       - /app/logs:/app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8041:8041"
    links:
       - cf-register-center
    restart: always
  cf-risk-center:
    image: cf-risk-center:latest
    build:
       context: ./cf-risk-center
#       args: 
#        - jarName=cf-risk-center.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8032:8032"
    links:
       - cf-register-center
    restart: always
  cf-credit-center:
    image: cf-credit-center:latest
    build:
       context: ./cf-credit-center
#       args: 
#        - jarName=cf-credit-center.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8015:8015"
    links:
       - cf-register-center
    restart: always
  cf-credit-gateway:
    image: cf-credit-gateway:latest
    build:
       context: ./cf-credit-gateway
#       args: 
#        - jarName=cf-credit-gateway.jar
    volumes:
       - /app/logs:/app/logs
#       - /app/logs
    privileged: true
#    log-driver: syslog
    ports:
       - "8010:8010"
    links:
       - cf-register-center
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.1.1
    volumes:
       - /app/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
       - /app/filebeat/data:/app/filebeat/data
       - /app/logs:/app/logs
    privileged: true
    restart: always
    container_name: filebeat
networks:
  default:
    external:
       name: over
