version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.4-management-alpine
    container_name: rabbitmq
    restart: always
    volumes: 
      - data:/var/lib/rabbitmq
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
volumes:
  data:
