version: '3'
services:
  dragonite:
    image: dragonitenetwork/dragonite-java:fwd-0.4.0-prx-0.4.0-alpine
    container_name: dragonite
    restart: always
    ports:
      - "152:152"
      - "152:152/udp"
      - "153:153"
      - "153:153/udp"
    environment:
      - DCMD
    command: ${DCMD}
  dragonite_bak:
    image: dragonitenetwork/dragonite-java:fwd-0.4.0-prx-0.4.0-alpine
    container_name: dragonite_bak
    restart: always
    ports:
      - "158:153"
      - "158:153/udp"
    environment:
      - BAKDCMD
    command: ${BAKDCMD}
